jenkins-slave:
  environment:
    JENKINS_USERNAME: jenkins
    JENKINS_PASSWORD: jenkins
    JENKINS_MASTER: http://jenkins-master:8080
  tty: true
  image: rancher/jenkins-slave
  links:
  - jenkins-master:jenkins-master
  privileged: true
  volumes:
  - /var/jenkins
  stdin_open: true
jenkins-master:
  restart: 'no'
  tty: true
  image: rancher/jenkins-master
  privileged: true
  stdin_open: true 
  ports: 
  - "127.0.0.1:8080:8080"
